services:
  kafka:
    image: apache/kafka:3.7.0
    hostname: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 2
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - gossip-network

  schema-registry:
    image: quay.io/apicurio/apicurio-registry-mem:2.5.0.Final
    hostname: schema-registry
    ports:
      - "8083:8080"
    networks:
      - gossip-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8122:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8080/apis/ccompat/v7
    depends_on:
      - kafka
      - schema-registry
    networks:
      - gossip-network

  neo4j:
    image: neo4j:latest
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
    networks:
      - gossip-network

  gossip-collector:
    container_name: gossip-collector
    build:
      context: .
    environment:
      KAFKA_BROKER: kafka:9092
      SCHEMA_REGISTRY_URL: http://schema-registry:8080/apis/ccompat/v7
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: password
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - kafka
      - schema-registry
      - neo4j
    networks:
      - gossip-network

networks:
  gossip-network:
    driver: bridge

volumes:
  kafka_data:
    driver: local
  neo4j_data:
    driver: local
