// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package tcp

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadGen_tcp returns the embedded CollectionSpec for gen_tcp.
func loadGen_tcp() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Gen_tcpBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load gen_tcp: %w", err)
	}

	return spec, err
}

// loadGen_tcpObjects loads gen_tcp and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*gen_tcpObjects
//	*gen_tcpPrograms
//	*gen_tcpMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadGen_tcpObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadGen_tcp()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// gen_tcpSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type gen_tcpSpecs struct {
	gen_tcpProgramSpecs
	gen_tcpMapSpecs
	gen_tcpVariableSpecs
}

// gen_tcpProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type gen_tcpProgramSpecs struct {
	ConsumeTcpEvent *ebpf.ProgramSpec `ebpf:"consume_tcp_event"`
}

// gen_tcpMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type gen_tcpMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// gen_tcpVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type gen_tcpVariableSpecs struct {
}

// gen_tcpObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadGen_tcpObjects or ebpf.CollectionSpec.LoadAndAssign.
type gen_tcpObjects struct {
	gen_tcpPrograms
	gen_tcpMaps
	gen_tcpVariables
}

func (o *gen_tcpObjects) Close() error {
	return _Gen_tcpClose(
		&o.gen_tcpPrograms,
		&o.gen_tcpMaps,
	)
}

// gen_tcpMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadGen_tcpObjects or ebpf.CollectionSpec.LoadAndAssign.
type gen_tcpMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *gen_tcpMaps) Close() error {
	return _Gen_tcpClose(
		m.Events,
	)
}

// gen_tcpVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadGen_tcpObjects or ebpf.CollectionSpec.LoadAndAssign.
type gen_tcpVariables struct {
}

// gen_tcpPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadGen_tcpObjects or ebpf.CollectionSpec.LoadAndAssign.
type gen_tcpPrograms struct {
	ConsumeTcpEvent *ebpf.Program `ebpf:"consume_tcp_event"`
}

func (p *gen_tcpPrograms) Close() error {
	return _Gen_tcpClose(
		p.ConsumeTcpEvent,
	)
}

func _Gen_tcpClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed gen_tcp_bpfel.o
var _Gen_tcpBytes []byte
