// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package http

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type gen_httpAcceptArgsT struct {
	_    structs.HostLayout
	Addr uint64
}

type gen_httpCloseArgsT struct {
	_  structs.HostLayout
	Fd uint32
}

type gen_httpConnInfoT struct {
	_      structs.HostLayout
	ConnId struct {
		_    structs.HostLayout
		Pid  uint32
		Fd   uint32
		Tsid uint64
	}
	WrBytes uint64
	RdBytes uint64
	IsHttp  bool
	_       [7]byte
	Skaddr  uint64
	Saddr   uint32
	Daddr   uint32
	Sport   uint16
	Dport   uint16
	_       [4]byte
}

type gen_httpDataArgsT struct {
	_   structs.HostLayout
	Fd  uint32
	_   [4]byte
	Buf uint64
}

// loadGen_http returns the embedded CollectionSpec for gen_http.
func loadGen_http() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Gen_httpBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load gen_http: %w", err)
	}

	return spec, err
}

// loadGen_httpObjects loads gen_http and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*gen_httpObjects
//	*gen_httpPrograms
//	*gen_httpMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadGen_httpObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadGen_http()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// gen_httpSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type gen_httpSpecs struct {
	gen_httpProgramSpecs
	gen_httpMapSpecs
	gen_httpVariableSpecs
}

// gen_httpProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type gen_httpProgramSpecs struct {
	SysEnterAccept  *ebpf.ProgramSpec `ebpf:"sys_enter_accept"`
	SysEnterAccept4 *ebpf.ProgramSpec `ebpf:"sys_enter_accept4"`
	SysEnterClose   *ebpf.ProgramSpec `ebpf:"sys_enter_close"`
	SysEnterRead    *ebpf.ProgramSpec `ebpf:"sys_enter_read"`
	SysEnterWrite   *ebpf.ProgramSpec `ebpf:"sys_enter_write"`
	SysExitAccept   *ebpf.ProgramSpec `ebpf:"sys_exit_accept"`
	SysExitAccept4  *ebpf.ProgramSpec `ebpf:"sys_exit_accept4"`
	SysExitClose    *ebpf.ProgramSpec `ebpf:"sys_exit_close"`
	SysExitRead     *ebpf.ProgramSpec `ebpf:"sys_exit_read"`
	SysExitWrite    *ebpf.ProgramSpec `ebpf:"sys_exit_write"`
}

// gen_httpMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type gen_httpMapSpecs struct {
	ActiveAcceptArgsMap *ebpf.MapSpec `ebpf:"active_accept_args_map"`
	ActiveCloseArgsMap  *ebpf.MapSpec `ebpf:"active_close_args_map"`
	ActiveReadArgsMap   *ebpf.MapSpec `ebpf:"active_read_args_map"`
	ActiveWriteArgsMap  *ebpf.MapSpec `ebpf:"active_write_args_map"`
	ConnInfoMap         *ebpf.MapSpec `ebpf:"conn_info_map"`
	SocketDataEvents    *ebpf.MapSpec `ebpf:"socket_data_events"`
}

// gen_httpVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type gen_httpVariableSpecs struct {
}

// gen_httpObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadGen_httpObjects or ebpf.CollectionSpec.LoadAndAssign.
type gen_httpObjects struct {
	gen_httpPrograms
	gen_httpMaps
	gen_httpVariables
}

func (o *gen_httpObjects) Close() error {
	return _Gen_httpClose(
		&o.gen_httpPrograms,
		&o.gen_httpMaps,
	)
}

// gen_httpMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadGen_httpObjects or ebpf.CollectionSpec.LoadAndAssign.
type gen_httpMaps struct {
	ActiveAcceptArgsMap *ebpf.Map `ebpf:"active_accept_args_map"`
	ActiveCloseArgsMap  *ebpf.Map `ebpf:"active_close_args_map"`
	ActiveReadArgsMap   *ebpf.Map `ebpf:"active_read_args_map"`
	ActiveWriteArgsMap  *ebpf.Map `ebpf:"active_write_args_map"`
	ConnInfoMap         *ebpf.Map `ebpf:"conn_info_map"`
	SocketDataEvents    *ebpf.Map `ebpf:"socket_data_events"`
}

func (m *gen_httpMaps) Close() error {
	return _Gen_httpClose(
		m.ActiveAcceptArgsMap,
		m.ActiveCloseArgsMap,
		m.ActiveReadArgsMap,
		m.ActiveWriteArgsMap,
		m.ConnInfoMap,
		m.SocketDataEvents,
	)
}

// gen_httpVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadGen_httpObjects or ebpf.CollectionSpec.LoadAndAssign.
type gen_httpVariables struct {
}

// gen_httpPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadGen_httpObjects or ebpf.CollectionSpec.LoadAndAssign.
type gen_httpPrograms struct {
	SysEnterAccept  *ebpf.Program `ebpf:"sys_enter_accept"`
	SysEnterAccept4 *ebpf.Program `ebpf:"sys_enter_accept4"`
	SysEnterClose   *ebpf.Program `ebpf:"sys_enter_close"`
	SysEnterRead    *ebpf.Program `ebpf:"sys_enter_read"`
	SysEnterWrite   *ebpf.Program `ebpf:"sys_enter_write"`
	SysExitAccept   *ebpf.Program `ebpf:"sys_exit_accept"`
	SysExitAccept4  *ebpf.Program `ebpf:"sys_exit_accept4"`
	SysExitClose    *ebpf.Program `ebpf:"sys_exit_close"`
	SysExitRead     *ebpf.Program `ebpf:"sys_exit_read"`
	SysExitWrite    *ebpf.Program `ebpf:"sys_exit_write"`
}

func (p *gen_httpPrograms) Close() error {
	return _Gen_httpClose(
		p.SysEnterAccept,
		p.SysEnterAccept4,
		p.SysEnterClose,
		p.SysEnterRead,
		p.SysEnterWrite,
		p.SysExitAccept,
		p.SysExitAccept4,
		p.SysExitClose,
		p.SysExitRead,
		p.SysExitWrite,
	)
}

func _Gen_httpClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed gen_http_bpfel.o
var _Gen_httpBytes []byte
