spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER}
    consumer:
      properties:
        schema.registry.url: ${SCHEMA_REGISTRY_URL}
  neo4j:
    uri: ${NEO4J_URI}
    authentication:
      username: ${NEO4J_USER}
      password: ${NEO4J_PASSWORD}
